<?php

require_once '../config/config.php';

require_once  '../config/functions.php';

require '../phpmailer/PHPMailerAutoload.php';


class changeBankDetails extends  Functions {


    private $data , $bankName , $bankAccountName , $bankAccountNumber , $userID , $currentAccountName;

    private $config;

    private $user_details;

    private $error , $successText = "success" , $errorText = "error";

    private $network_connection_error = "please check your network connection";

    private $email_success_message = "Please click the link sent to your email address, to confirm change";
    private $sucess_message = "Account details saved successfully";

    private $request_time , $verification_code;

    function __construct()
    {
        parent::__construct();
        $this->config = new WebsiteDetails();
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }


    public function  isReady () {

        return (!empty($this->data = json_decode($_POST["data"] , true) ));
    }


    private function setDetails () : bool {


        $this->bankName = $this->data["bankName"];
        $this->bankAccountName = ucwords($this->data["bankAccountName"]);
        $this->bankAccountNumber = $this->data["bankAccountNumber"];
        $this->userID = $this->data["userID"];
        $this->currentAccountName = $this->data["currentAccountName"];
        $this->request_time = time();
        $this->verification_code = $this->generateID($this->bank_details_verification_code_length);
        $this->user_details = $this->fetch_data_from_table($this->users_table_name , "user_id" , $this->userID)[0];

        $action = (!$this->record_exists_in_table($this->pending_bank_details_table_name , 'verification_code' , $this->verification_code))?true : $this->setDetails();

        return $action;
    }



    private function isCurrentBankDetails()  {


       if($this->bankName == $this->user_details["bank_name"] && $this->bankAccountNumber == $this->user_details["account_number"]){
           $this->update_record($this->users_table_name , 'account_name' , $this->bankAccountName , 'user_id' , $this->userID);
           return true;
       }
       return false;

    }

    private  function  userAccounDetailsAlreadyPending() : bool {
        return $this->record_exists_in_table($this->pending_bank_details_table_name ,'user_id' , $this->userID);
    }

    private  function userAccountDetailsAlreadySet() : bool  {

        return $this->user_details["account_name"] != "0";
    }

    private function updateUserBankAccountDetailsForTheFirstTime() : bool {

        return $this->update_multiple_fields($this->users_table_name , ["bank_name" => $this->bankName, "account_name" => $this->bankAccountName, "account_number" => $this->bankAccountNumber] , "user_id='{$this->userID}'");

}


    private function  tryUpdateUserPendingDetails () : bool {

        return ($this->userAccounDetailsAlreadyPending())? $this->update_multiple_fields($this->pending_bank_details_table_name ,
            ["user_id" => $this->userID, "bank_name" => $this->bankName, "account_name" => $this->bankAccountName, "account_number" => $this->bankAccountNumber, "verification_code" => $this->verification_code, "last_requested" => $this->request_time]
            , "user_id = '{$this->userID}'")
            : $this->insert_into_table($this->pending_bank_details_table_name , ["user_id" => $this->userID, "bank_name" => $this->bankName, "account_name" => $this->bankAccountName, "account_number" => $this->bankAccountNumber, "verification_code" => $this->verification_code, "last_requested" => $this->request_time] , "user_id = '{$this->userID}'");
    }



    private function sendEmailToUser() {
        $mail = new PHPMailer;
        $time = time();

        $date = date('d-m-Y' , $time);


        // include  '../emails/basic_emails/verification_email.php';
        // include  '../emails/html_emails/verification_email.php';
        $time_string = date('h:i:s a' , $time);


        $html_email_body = <<<HTML_EMAIL_BODY

<!DOCTYPE html>
<html lang = 'en-us'>
<head>
<style type='text/css'>
#mail-logo-image {
width : 16px;
height : 16px;
position:relative;
left : 93%;

}

#email-text , #not-user-message{
font-family: 'Helvetica Neue Light',Helvetica,Arial,sans-serif;
font-size: 16px;
padding: 0px;
margin: 0px;
font-weight: normal;
line-height: 22px;
color : #222;
margin-top : 20px;
}


body {

background-color: #f5f8fa;
margin: 0;
padding: 0;

}
#final-step {

color : #222;
font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;
font-size:24px;
padding:0px;
margin:0px;
font-weight:bold;
line-height:32px;
}

#date {

  display : none;
}


@media only screen and (max-width: 600px) {

#main-mail-container-div {

width : 80%;
}


}

#container{
background-color : #e1e8ed;
}

#main-mail-container-div {

margin-left : auto;
margin-right: auto;
background-color : #fff;
width : 420px;
padding : 15px;
}
#confirmation-link{

font-size: 16px;
font-family: 'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;
color: #ffffff;
text-decoration: none;
border-radius: 4px;
padding: 11px 30px;
border: 1px solid #1da1f2;
display: inline-block;
font-weight: bold;
background-color: rgb(29, 161, 242);
margin-top : 20px;
}

#not-user-message {

font-size: 12px;


}

#site-address {
color: #8899a6;

font-family: 'Helvetica Neue Light',Helvetica,Arial,sans-serif;

font-size: 12px;

font-weight: normal;

line-height: 16px;

text-align: center;
width : 180px;
margin : auto;
}

</style>
</head>

<body>
<div id ='container'>
<div id = 'main-mail-container-div'>

<p id = 'final-step'>Final step...</p>
<p id = 'email-text'>
Dear {$this->user_details['fullname']} , <br /> <br />
You recently requested to change your bank account details  <strong>{$this->user_details['email']}</strong>. It's easy — just click the button below. 

</p>

<a href = "{$this->config->SiteNameWithHttps}/play?action=update_bank_details&code={$this->verification_code}" title='Confirm change' id = 'confirmation-link'>Confirm Bank Details</a>

<p id = 'not-user-message'>

This email was automatically sent to you by {$this->config->SiteName}.Please do not reply to this email. If you have any question, do not hesistate to <a href="{$this->config->SiteNameWithHttps}">contact us.</a>  Thank you.
</p>
<p id = 'site-address'>
{$this->config->SiteName} International ﻿Company.
{$this->config->HeadOffice}
</p>
<br />
<span id = "date">{$time_string}</span>;

</div>


</div>

</body>

</html> 



HTML_EMAIL_BODY;
        $html_email_body;
        $basic_email_body = <<<BASIC_EMAIL_BODY

<!DOCTYPE html>
<html lang='en-us' dir='ltr'>
<body>

Dear {$this->user_details['fullname']} ,<br /><br />

You recently requested to change your bank account details  <strong>{$this->user_details['email']}</strong>. It's easy — just click the link below. 


<br />
<br/>
<strong>Bank Details Reset Link</strong><br>
<a href = "{$this->config->SiteNameWithHttps}/play?action=update_bank_details&code={$this->verification_code}" title='Confirm change' id = 'confirmation-link'>Confirm Bank Details</a>

<br /><br />

This email was automatically sent to you by {$this->config->SiteName} .Please do not reply to this email.
If you have any question, do not hesistate to <a href="{$this->config->SiteNameWithHttps}">contact us</a>.
Thank you.<br /><br />



The {$this->config->SiteName} Team <br /> <br />
<span style="display: none;">{$time_string}</span> 
</body>
</html>

BASIC_EMAIL_BODY;


        $mail->isSMTP();                                      // Set mailer to use SMTP
        $mail->Host = $this->config->PrimaryEmailServer;  // Specify main and backup SMTP servers
        $mail->SMTPAuth = true;
//$mail->SMTPDebug = 3;                              // Enable SMTP authentication
        $mail->Username = $this->config->PrimaryEmail;                 // SMTP username
        $mail->Password = $this->config->PrimaryEmailPassword;                           // SMTP password
        $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
        $mail->Port = 587;                                    // TCP port to connect to
        $site_author = $this->config->SiteAuthor;
        $primary_email = $this->config->PrimaryEmail;
        $primary_email_server = $this->config->PrimaryEmailServer;
        $primary_email_password = $this->config->PrimaryEmailPassword;

        try {
            $mail->setFrom($primary_email_server, "{$site_author} From {$this->config->SiteName}");
        } catch (phpmailerException $e) {
            //  echo $e->getMessage();
            return false;
        }

        $mail->addAddress($this->user_details['email'], $this->user_details['fullname']);     // Add a recipient
//$mail->addAddress('ellen@example.com');               // Name is optional
        $mail->addReplyTo($primary_email, $this->config->SiteName);

// $mail->addCC('cc@example.com');
//$mail->addBCC('bcc@example.com');

//$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
//$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
        $mail->isHTML(true);                                  // Set email format to HTML
        $mail->Subject = "Confirm new Bank Details for  {$this->config->SiteName} account, {$this->user_details['fullname']}";
        $mail->Body = $html_email_body;
        $mail->AltBody = $basic_email_body;
        if(!$mail->send()) {
            //  echo 'Mailer Error: ' . $mail->ErrorInfo;
            return false;
        } else {
            return  true;
        }


    }




    public  function  Processor ()
    {


        if ($this->isReady()) {
            $this->setDetails();

            if ($this->isCurrentBankDetails()) {

                $this->error = Array($this->errorText => $this->sucess_message, $this->successText => "1");
                $this->error = json_encode($this->error);

                return $this->error;
            } elseif ($this->userAccountDetailsAlreadySet()) {


                $this->tryUpdateUserPendingDetails();
                if($this->sendEmailToUser()) {
                    $this->error = Array($this->errorText => $this->email_success_message, $this->successText => "1");
                    $this->error = json_encode($this->error);

                    return $this->error;
                }
                else {

                    $this->error = Array($this->errorText => $this->network_connection_error, $this->successText => "0");
                    $this->error = json_encode($this->error);

                    return $this->error;
                }


            }

            else {
                $this->updateUserBankAccountDetailsForTheFirstTime();
                $this->error = Array($this->errorText => $this->sucess_message, $this->successText => "1");
                $this->error = json_encode($this->error);

                return $this->error;
            }

        }
    }



}

$changeBankDetails = new changeBankDetails();
echo  $changeBankDetails->Processor();


?>