<?php

require_once '../config/config.php';
require_once '../config/functions.php';



class FundAccount extends  Functions{

    private  $data , $amount , $userID , $type , $reference_code , $date , $user_details , $currentAccountBalance , $newAccountBalance;


    private $successText = "success" , $errorText = "error" , $error , $success_message = "Payment will be made to the account details you provided in less than 15min.";



    function __construct()
    {


        parent::__construct();
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }



    private function  isReady() : bool  {

        return !empty($this->data = json_decode($_POST["data"] , true)) or !is_null($this->data= json_decode($_POST["data"] , true));
    }


    private function setDetails () : bool  {
        $this->amount = $this->data["amount"];
        $this->userID= $this->data["userID"];
        $this->type = $this->data["type"];
        $this->reference_code =  $this->data["referenceCode"];
        $this->date = date("d-M-Y h:i:s A");
        $this->user_details = $this->fetch_data_from_table($this->users_table_name , "user_id" , $this->userID)[0];
        $this->currentAccountBalance = intval($this->user_details[$this->type]);
        $this->newAccountBalance = $this->currentAccountBalance - intval($this->amount);;

        return true;
    }


    private function  update_account_balance () : bool {

        return $this->update_record($this->users_table_name , $this->type , $this->newAccountBalance , 'user_id' , $this->userID);
    }

    private function store_in_records () : bool  {

        return $this->insert_into_table($this->withdrawals_table_name , ["user_id" => $this->userID , "reference_code" => $this->reference_code , "time_stamp" => $this->date , "amount" => $this->amount , "bank_name" => $this->user_details["bank_name"] , "account_name" => $this->user_details["account_name"] , "account_number" => $this->user_details["account_number"] , "type" => $this->type]);
    }

    public final function Processor() {
        if($this->isReady() && $this->setDetails())
            $this->update_account_balance();
        $this->store_in_records();

        return $this->error = json_encode(Array($this->successText => "1" , $this->errorText => $this->success_message));


    }




}

$fundAccount = new FundAccount();

echo $fundAccount->Processor();



?>