<?php
require_once $_SERVER['DOCUMENT_ROOT'].'/config/config.php';
require_once $_SERVER['DOCUMENT_ROOT'].'/funcs/user_functions.php';


//if(!$user_functions->isLoggedInUser()) header('location: /404');
//$default_username = $functions->fetch_data_from_table($functions->users_table_name , 'username' , $website_details->defaultUsername)[0]['user_id'];
//if($_COOKIE[$website_details->CookieUserKey] != $default_username)header('location: /404');
?>
<!DOCTYPE html>
<html lang="en-us" dir = "ltr">
<head>
    <meta charset="utf-8" />
    <meta name = "description" content="Admin payment page" />
    <meta name="keywords" content="Payment" />
    <link rel="stylesheet" type="text/css" href="<?php echo $website_details->CSS_FOLDER;?>bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php print $website_details->CSS_FOLDER;?>cairo.css" />
    <link rel="stylesheet" type="text/css" href="<?php print $website_details->CSS_FOLDER;?>bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php print $website_details->CSS_FOLDER;?>font-awesome.min.css" />
    <script type="text/javascript" language = "JavaScript" src="<?php echo $website_details->JS_FOLDER;?>jquery-min.js"></script>
    <script type="text/javascript" language = "JavaScript" src="<?php echo $website_details->JS_FOLDER;?>bootstrap.min.js"></script>
    <title><?php echo  $website_details->SiteName;?> - Site statistics</title>
    <script type="text/javascript" language="JavaScript" src="<?php echo $website_details->JS_FOLDER?>defaults.js"></script>







</head>

<body>
<div class="container">
    <h2>Welcome to our site statistics page</h2>
    <p>The table below contains our overall site statistics, the data below reflects exactly how users interact with this website.</p>

    <div class="table-responsive">
        <table class="table table-hover table-condensed">

            <thead>
            <tr>

                <th>Key </th>
                <th>Value </th>

            </tr>
            </thead>

            <tbody>

            <?php

            class Statistics extends Functions {

                public $data;
                public function __construct()
                {
                    parent::__construct();
                }

                public function __destruct()
                {
                    parent::__destruct(); // TODO: Change the autogenerated stub
                }


                public function DisplayData () : string  {
                    $results = $this->fetch_data_from_table($this->stats_table_name , 'id' , '1')[0];

                    $html = "";
                    foreach ($results as $key => $value) {
                        $hideID = ($key == "id") ? "style = 'display:none'": null;
                        $key = ucfirst(str_replace("_" , " " , $key));

                        $html.="<tr $hideID><td><strong>$key</strong></td><td>$value</td></tr>";



        }

        return $html;





                }


            }

            $statistics =  new Statistics();
            print($statistics->DisplayData());


            ?>
            </tbody>
                    </table>
    </div

</div>
</body>
</html>